# Generated by Django 5.0.6 on 2024-05-20 06:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_managers_user_is_deleted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='profile/'),
            preserve_default=False,
        ),
    ]
